version: 2
jobs:
  build:
          working_directory: ~/android-code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Copy Licences
          command: cp -r licenses/. $ANDROID_HOME/licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testAllModulesTravis
      - store_artifacts:
              path: test-app/build/reports
          destination: reports
      - store_test_results:
              path: test-app/build/test-results
